-- Schema para testes - forçar ENUMs como VARCHAR
DROP TABLE IF EXISTS TB_ITEM_PEDIDO;
DROP TABLE IF EXISTS TB_PEDIDO;
DROP TABLE IF EXISTS TB_PRODUTOS;
DROP TABLE IF EXISTS TB_CLIENTE;
DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER (
    ID VARCHAR(36) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE TB_CLIENTE (
    ID VARCHAR(36) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    TELEFONE VARCHAR(255),
    CPF VARCHAR(255) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS (
    ID VARCHAR(36) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    PRECO DECIMAL(10,2) NOT NULL,
    CATEGORIA VARCHAR(255),
    QUANTIDADE_ESTOQUE BIGINT,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_PEDIDO (
    ID VARCHAR(36) NOT NULL,
    ID_CLIENTE VARCHAR(36) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE TB_ITEM_PEDIDO (
    ID VARCHAR(36) NOT NULL,
    PEDIDO_ID VARCHAR(36) NOT NULL,
    PRODUTO_ID VARCHAR(36) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUTO_ID) REFERENCES TB_PRODUTOS(ID) ON DELETE CASCADE
);
